# Generated by Django 4.2.7 on 2023-11-07 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.list')),
            ],
        ),
    ]
